/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_samples_facedetect_FastCodeTracker */

#ifndef _Included_org_opencv_samples_facedetect_FastCodeTracker
#define _Included_org_opencv_samples_facedetect_FastCodeTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opencv_samples_facedetect_FastCodeTracker
 * Method:    nativeCreateObject
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_opencv_samples_facedetect_FastCodeTracker_nativeCreateObject
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_opencv_samples_facedetect_FastCodeTracker
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_FastCodeTracker_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_opencv_samples_facedetect_FastCodeTracker
 * Method:    nativeStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_FastCodeTracker_nativeStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_opencv_samples_facedetect_FastCodeTracker
 * Method:    nativeStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_FastCodeTracker_nativeStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_opencv_samples_facedetect_FastCodeTracker
 * Method:    nativeDetectAndDisplay
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_FastCodeTracker_nativeDetectAndDisplay
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
